### ISSUE TITLE
How to transform a field, such as add a prefix/suffix?

### ISSUE THREAD

**Issue by douglascayers** [davidmreed/amaxa#29]
👋 Hi, I learned about your project via [your tweet](https://twitter.com/aoristdual/status/1242816613168136196?s=12).

This looks interesting. I have a use case where I need to copy some parent-child relationships from one org to another and perform a **transform** step to append a suffix to some text fields.

I didn't readily see how [in the docs](https://amaxa.readthedocs.io/en/latest/operations.html) to perform a transform other than [uppercase, lowercase, or strip](https://github.com/davidmreed/amaxa/blob/master/amaxa/transforms.py).

Are there other transform capabilities to further change values?

Thanks

**Comment by davidmreed** [comment]
Doug, I've actually just been discussing with another user ways to add extensibility to Amaxa's transforms, which are currently (and more or less arbitrarily) limited to the four functions in `transforms.py`. I linked the issue above.

I don't think this is a big lift and I know multiple folks are interested in it so I would like to prioritize. Do you have any thoughts on the design linked above?

In the interim before that feature becomes part of mainline Amaxa, the use case you articulated would be very easy to patch in on a local virtual environment, and I'd be happy to help set that up. Drop me a line? d.reed@salesforce.com.

**Comment by davidmreed** [comment]
@douglascayers I just merged in code that I think will hit this mark. It adds prefix and suffix transforms, as well as allowing for further extensibility in separate modules. Let me know if you think that'll help.

**Comment by douglascayers** [comment]
Wow, thanks for the quick update, @davidmreed! I was just reading the docs to set up my first export and came across the update that mentions the prefix/suffix transforms. At first I felt sheepish thinking "how did I miss this?!" then came back to check recent commits and lo and behold you were THAT fast. Thanks :)

**Comment by douglascayers** [comment]
@davidmreed What's the best way for me to get the latest updates? I currently installed https://github.com/davidmreed/amaxa/releases/tag/0.9.5 for macOS, as that's the latest release. Or should I use `pip install amaxa`? Thanks

**Comment by davidmreed** [comment]
@douglascayers  I haven't done an 0.9.6 release yet, so I'd recommend running off `master` in a virtual environment. Clone the repo, cd into it, then do

```bash
python3 -m venv venv
. venv/bin/activate
pip install poetry
poetry install
```

and that should get you running (so long as you have the venv activated, of course).

I'll get 0.9.6 out shortly. Let me know if you hit any snags!
