### ISSUE TITLE
Allow extraction of the same object as both parent and child

### ISSUE THREAD

**Issue by eranvaizel** [davidmreed/amaxa#46]
I've tried an extraction where a base object is defined in the beginning of the op file with the `extract: ids: ` attribute. However, I also need to extract this object down the line a a child object. Listing the same object further down in the op file, this time with the `extract: descendents: true` attribute did not work as expected - the only extracted record of that object was the anchor record. Is this a limitation or a bug?

Thanks!
Eran

**Comment by davidmreed** [comment]
@eranvaizel Could you share a representative sample of your operation definition?

**Comment by eranvaizel** [comment]
Yep. I'm trying Amaxa on our custom data model which is pretty complex. But let's talk in simple main stream objects. Let's say at the first level I'm extracting a specific account with a specific Id. Next, I'm extracting all of its opportunities using extract: descendents: true. However, opportunity also has a lookup to another account, say secondary_customer__c or something. There's no way to make that account get extracted as well, as far as I can this. I just ran into the outside-lookup-behavior attribute and thought that might be the solution, but apparently all it can control is whether the value in opportunity's secondary_customer__c will be extracted or not. It doesn't actually help recursively extract that account, that wasn't included in the first operation. 
I hope that makes sense?

**Comment by davidmreed** [comment]
Ah, thank you for elaborating. Yes, your understanding of the functionality is correct - Amaxa currently has no feature to recurse though an operation definition to include records targeted by outside lookups.

In many situations, you can restructure your operation definition to make these records end up as dependents or descendents. However, the situation you sketch out is going to be rather tricky, and I'm not sure Amaxa can do that today without significantly changing your operation design.

**Comment by davidmreed** [comment]
cf. the skeletal issue #21.

**Comment by davidmreed** [comment]
I'll close this issue for now but happy to discuss further.
