### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by angad-pathak** [davidmreed/amaxa#48]
On Windows 10,
When try to extract the data (Case object) using smart, get the following error:

```
Case: starting extraction..
Unexpected exception 'charmap' codec can't encode character '\u0308' in position 3736: character maps to <undefined> occurred.
```

Please suggest solution for this issue.

**Comment by davidmreed** [comment]
This is most likely a bug in Amaxa caused by failure to account for a default encoding other than UTF-8 on some Windows machines. I will investigate.

**Comment by angad-pathak** [comment]
Is there a Windows Settings that I should try changing?

**Comment by BenjaminTetreault** [comment]
Any update on this ? Stumbled on the same issue : 

Unexpected exception 'charmap' codec can't encode character '\u202d' in position 309: character maps to <undefined> occurred.

**Comment by BenjaminTetreault** [comment]
Error is on line 130 of extract_operation.py, add the correct encoding : 

file_handle = open(entry["file"], "w", newline="", encoding='utf-8')

**Comment by davidmreed** [comment]
There's a whole bunch of locations where this can happen. I apologize for letting this sit so long. I am preparing a fix now.
