### ISSUE TITLE
Error while Loading in my sandbox

### ISSUE THREAD

**Issue by ghost** [davidmreed/amaxa#52]
Hi, i did different an Extract operations for my SObjects and i obtained different (Sobject.csv) file(In a sequential way). But i was trying to Load all the Sobjects  the same way i did with the extraction process. But during the Load, i had this kind of error.

![erreur](https://user-images.githubusercontent.com/90350597/136052544-46c36f8b-36b6-4fe6-b113-73df078c5a22.PNG)

How do i solve this problem?
Thx!

**Comment by davidmreed** [comment]
Looks like Amaxa is causing an exception while trying to report errors from an API call. Can you inspect the Bulk Job status in your org's Setup page? You should be able to see whether jobs were actually created and if so what the specific errors were there. I'll try to track down this bug in error reporting.
