### ISSUE TITLE
Errors with credentials

### ISSUE THREAD

**Issue by ghost** [davidmreed/amaxa#53]
Hi, I also recently update amaxa with the newer version and i have a TypeError with the credentials(i use : username and Password) template. 
Here, the example of the template: 
![credentialTemplate](https://user-images.githubusercontent.com/90350597/136069104-49ae5be2-f8ea-42cb-8cfc-e7ef9f979019.PNG)

here, the error that i have.
![Error](https://user-images.githubusercontent.com/90350597/136068412-a28acbd2-85b3-4ec7-8f42-634b9ebad2b7.PNG)

Thx.

**Comment by davidmreed** [comment]
Looks like a bug, sorry about that. You can go back to Amaxa 0.9.6 for a quick fix and I'll try to get a new release out tonight.

**Comment by ghost** [comment]
Thx a lot @davidmreed .  I will go back to Amaxa 0.9.6, you doing a good job. If anything wrong happen, i'll leave a comment. #Respect.

**Comment by davidmreed** [comment]
Both of the issues you reported _should_ be fixed in Amaxa 0.9.8, which I just released. Thanks for using Amaxa and I appreciate the bug reports!
