### ISSUE TITLE
Using The SOQL syntax "LIMIT" not working

### ISSUE THREAD

**Issue by ghost** [davidmreed/amaxa#55]
Hello @davidmreed , i don't know if it is an issue but how do we LIMIT the number or records?

 Example: i would like to have 100 Accounts with associated Asset, Case, Contract, Contact, etc.

Thx.

**Comment by davidmreed** [comment]
I would expect this to work if you append the `LIMIT` clause to a [`query`](https://amaxa.readthedocs.io/en/latest/operations.html#which-records-do-we-want-to-extract) definition, i.e.,

    query: 'Industry = "Non-Profit" LIMIT 100'

**Comment by ghost** [comment]
Hello @davidmreed  it works. Thx you. But is there a way to skip this kind of errors : "INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY: insufficient access rights on cross-reference id", it happens  during a load of a sObject.

**Comment by davidmreed** [comment]
That error usually doesn't have much to do with Amaxa. It's related to record-level visibility and can be quite tricky to triage. I don't know if [outside reference behavior](https://amaxa.readthedocs.io/en/latest/references.html#outside-references) might be useful or not. It's very data-dependent.
